#!/usr/bin/env bash

source venv/bin/activate

case "$1" in

    # Run development with jurigged
    # (this is essentially black magic that lets you live-edit code)
    dev)       python3 -m jurigged main.py;;

    # Run production
    prod)      python3 main.py;;

    # Show usage
    *)         echo "Usage: $0 {dev|prod}";;

esac
